version: "3.7"
services:
  api:
    image: is_backend:1.0.0
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=DB
    volumes:
      - ./app:/usr/src/app

  db:
    image: mysql:8.0.21
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=DB
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
