version: "3.4"
services:
  tests:
    build:
      target: dev
      context: .
      dockerfile: ./Dockerfile
    image: is_test
    environment:
      - TYPE=TEST
      - ENVIRONMENT=DEV
      - DATABASE_HOST=db_test
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root_1234Azumo
      - DATABASE_NAME=DB
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db_test

  db_test:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_1234Azumo
      - MYSQL_DATABASE=DB
    volumes:
      - db_test_data:/var/lib/mysql

volumes:
  db_test_data:
