AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "fastAPI aws lambda example"

Resources:
  FastapiExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Properties:
            RestApiId:
              Ref: FastapiExampleGateway
            Path: /{proxy+}
            Method: ANY
          Type: Api
      FunctionName: fastapi-lambda
      CodeUri: ./
      Handler: app.main.handler
      Runtime: python3.8
      Timeout: 300
      MemorySize: 128
      Description: fastAPI aws lambda example
      Role: !Sub arn:aws:iam::717697772587:role/fastapilambdarole
      Environment:
        Variables:
          API_HOST:
          SECRET_KEY:
          JWT_ALGORITHM:
          JWT_EXPIRE_MINUTES:
          DATABASE_HOST:
          DATABASE_USER:
          DATABASE_PASSWORD:
          DATABASE_NAME:

  FastapiExampleGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      OpenApiVersion: "3.0.0"
